# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AC3.2-MidtermElements' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AC3.2-MidtermElements
  pod 'Kingfisher', '~> 3.0'
  
end
